services:
  holos-frontend:
    build:
      context: /var/www/holos.frontend
      dockerfile: dockerfile
    ports:
      - "${APP_PORT}:${NGINX_PORT}"
    networks:
      - holos-network

networks:
  holos-network:
    driver: bridge